Import Library

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

Import DataSet

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/DhruvBhirud/datasets/main/Womens%20Clothing%20E-Commerce%20Reviews.csv')

In [5]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


Missing Value

In [8]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [9]:
df[df['Review Text']==""]=np.NaN

In [10]:
df['Review Text'].fillna("No Review",inplace=True)

In [11]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [12]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

Define y and X

In [13]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [14]:
X = df['Review Text']

In [15]:
y = df['Rating']

In [16]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64


Train Test Split

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, stratify=y,random_state=42529)

Get Feature Text Conversion to Tokens

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
cv = CountVectorizer(lowercase = True, analyzer='word', ngram_range=(2,3),stop_words='english',max_features=5000)
X_train = cv.fit_transform(X_train)
cv.get_feature_names_out()

array(['00 petite', '10 12', '10 bought', ..., 'years come', 'years old',
       'yoga pants'], dtype=object)

In [22]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
X_test = cv.fit_transform(X_test)
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 dresses', ..., 'years old',
       'yellow color', 'yoga pants'], dtype=object)

In [24]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

Get Model Train

In [25]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

Get Model Prediction

In [26]:
y_pred = model.predict(X_test)
y_pred

array([4., 5., 4., ..., 3., 4., 1.])

Get Probability of Each Predict Class

In [27]:
model.predict_proba(X_test)

array([[0.01597287, 0.06247668, 0.02343906, 0.86805191, 0.03005948],
       [0.01938616, 0.03618749, 0.01366139, 0.02494917, 0.9058158 ],
       [0.12714164, 0.31224624, 0.02402702, 0.4310927 , 0.10549239],
       ...,
       [0.12935707, 0.07677888, 0.54537581, 0.10858167, 0.13990657],
       [0.01039322, 0.00244866, 0.02592397, 0.69603597, 0.26519819],
       [0.3715833 , 0.28173991, 0.19139055, 0.14724676, 0.00803948]])

Get Model Evaluation

In [28]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))

[[  17   24   29   47  136]
 [  46   60   52   92  220]
 [  91   87  115  184  384]
 [ 156  153  193  334  687]
 [ 395  302  375  737 2130]]


In [29]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.02      0.07      0.04       253
         2.0       0.10      0.13      0.11       470
         3.0       0.15      0.13      0.14       861
         4.0       0.24      0.22      0.23      1523
         5.0       0.60      0.54      0.57      3939

    accuracy                           0.38      7046
   macro avg       0.22      0.22      0.22      7046
weighted avg       0.41      0.38      0.39      7046



Recategories Rating as Poor 0 and Good 1

In [30]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [31]:
df.replace({'Rating': {1:0,2:0,3:0,4:1,5:1}}, inplace=True)

In [32]:
y=df['Rating']

In [33]:
X=df['Review Text']

Train Test Split

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.7,random_state=42529)

Get Feature Text Conversion to Tokens

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)
X_train = cv.fit_transform(X_train)
X_test = cv.fit_transform(X_test)

Get Model ReTrain

In [36]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

Get Model Prediction

In [37]:
y_pred = model.predict(X_test)
y_pred

array([1., 1., 0., ..., 1., 1., 1.])

Get Model Evaluation

In [38]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_pred))

[[ 459 1187]
 [ 846 4554]]


In [39]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.35      0.28      0.31      1646
         1.0       0.79      0.84      0.82      5400

    accuracy                           0.71      7046
   macro avg       0.57      0.56      0.56      7046
weighted avg       0.69      0.71      0.70      7046

